repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: poetry run ruff check .
        language: system
        pass_filenames: false
      - id: ruff-fix
        name: ruff-fix
        entry: poetry run ruff check --fix .
        language: system
        pass_filenames: false
      - id: black
        name: black
        entry: poetry run black .
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        pass_filenames: false
      - id: codespell
        name: codespell
        entry: poetry run codespell
        language: system
        files: ^(src|tests)/.*\.(py|md|rst|txt)$
        pass_filenames: true
      - id: forbid-merge-conflict
        name: forbid-merge-conflict-markers
        entry: grep -R "<<<<<<< HEAD" -n .
        language: system
        pass_filenames: false
